language: cpp
compiler: gcc
env:
    global:
        - WORKING_DIR=${TRAVIS_BUILD_DIR}
        - LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/lib
before_install:
    - pip install --user cpp-coveralls
    - svnadmin create ${TRAVIS_BUILD_DIR}/svn
    - svn mkdir file://${TRAVIS_BUILD_DIR}/svn/trunk file://${TRAVIS_BUILD_DIR}/svn/tags file://${TRAVIS_BUILD_DIR}/svn/branches -m 'initial structure'
script: make -C src all && ${TRAVIS_BUILD_DIR}/bin/test_desitemplate_cpp
after_success: coveralls --exclude lib --exclude doc --exclude etc --gcov-options '\-lp'
