language: cpp
compiler:
    - gcc
env:
    - WORKING_DIR=${TRAVIS_BUILD_DIR}
before_install:
    - pip install --user cpp-coveralls
script:
    - make && bin/template_version
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
