language: cpp
compiler: gcc
env:
    global:
        - WORKING_DIR=${TRAVIS_BUILD_DIR}
        - LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/lib
before_install: pip install --user cpp-coveralls
script: make -C src all && ${TRAVIS_BUILD_DIR}/bin/test_desitemplate_cpp
after_success: coveralls --exclude lib --exclude doc --exclude etc --gcov-options '\-lp'
