language: cpp
compiler: gcc
env:
    global:
        - WORKING_DIR=${TRAVIS_BUILD_DIR}
        - LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/lib
before_install:
    - pip install --user cpp-coveralls
script:
    - make -C src all && ${TRAVIS_BUILD_DIR}/bin/template_version
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
